Completing the parse only functionality. Example usage below.
[compiler] $ ./boa.sh -p
no valid input files found - did you use the --in option?
usage: Boa Parser
 -i,--in <arg>     file(s) to be parsed (comma-separated list)
 -l,--libs <arg>   extra jars (functions/aggregators) to be compiled in
[compiler] $ ./boa.sh -p -i
./test/parsing/errors/visitor-missing-before.boa 
visitor-missing-before.boa: compilation failed: Encountered parser error
"[@6,24:24='n',<76>,2:1]" at line 2, column 1. error: visit statements
must start with 'before' or 'after'
    n: Revision -> stop;
    ^
	at unknown stack
visitor-missing-before.boa: compilation failed: Encountered parser error
"[@12,46:46='n',<76>,3:1]" at line 3, column 1. error: visit statements
must start with 'before' or 'after'
    n: ChangedFile -> stop;
    ^
	at unknown stack